name: Feature Request
description: Suggest a new feature for wtview
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an idea to improve wtview! Please fill out the sections below to help us understand your feature request.
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Describe the problem or use case that this feature would address
      placeholder: |
        Currently, wtview doesn't support...
        This makes it difficult to...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe how you would like the feature to work
      placeholder: |
        The feature could work by:
        1. ...
        2. ...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative approaches you've considered
      placeholder: |
        - Alternative 1: ...
        - Alternative 2: ...
    validations:
      required: false
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature for you?
      options:
        - "Low: Nice to have"
        - "Medium: Would improve workflow"
        - "High: Critical for use case"
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or references here
      placeholder: "Additional context goes here..."
    validations:
      required: false
